import Link from "next/link";
import { ArrowLeft, BookOpen } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-900 py-20 px-6">
      <div className="max-w-4xl mx-auto bg-white border border-slate-200 rounded-3xl p-10 shadow-sm">
        <Link href="/" className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-700 font-bold mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>
        <div className="flex items-center gap-3 mb-8">
          <BookOpen className="w-10 h-10 text-blue-600" />
          <h1 className="text-4xl font-black uppercase tracking-tight">Terms of Service</h1>
        </div>
        
        <div className="prose prose-slate max-w-none prose-h2:text-2xl prose-h2:font-bold prose-h2:mt-8 prose-h2:mb-4">
          <p className="text-sm text-slate-500 mb-8 font-medium">Last Updated: July 10, 2026</p>

          <h2>1. Acceptance of Terms</h2>
          <p>By accessing and using Nexus, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform.</p>

          <h2>2. Use of Platform & Acceptable Conduct</h2>
          <p>You agree to use Nexus only for lawful business purposes. You must not:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Post fraudulent, illegal, or deceptive marketplace listings.</li>
            <li>Use the AI tools to generate harmful or malicious content.</li>
            <li>Attempt to bypass billing or credit limits.</li>
          </ul>

          <h2>3. Intermediary Liability (Marketplace)</h2>
          <p>Nexus acts as an intermediary for B2B transactions as defined under applicable IT laws (e.g., Section 79 of the Indian IT Act). We provide the platform but do not guarantee the quality, safety, or legality of items listed by third parties. We reserve the right to remove any content flagged by our automated systems or user reports.</p>

          <h2>4. No Financial or Legal Advice</h2>
          <p>The strategic roadmaps, equity funding calculations, and business plans generated by our AI are for informational purposes only. They do not constitute licensed financial, legal, or accounting advice. You should consult certified professionals before making business decisions.</p>

          <h2>5. Limitation of Liability</h2>
          <p>In no event shall Nexus be liable for any indirect, incidental, special, or consequential damages arising out of your use of the platform.</p>

          <h2>6. Contact Us</h2>
          <p>For support or inquiries regarding these terms, please contact <strong>NexusB2BAI@outlook.com</strong>.</p>
        </div>
      </div>
    </div>
  );
}
